image: bverhagen/pacman-aur-wrapper
variables:
    GIT_SUBMODULE_STRATEGY: normal
    PREFIX: package-src
    BIN_PREFIX: package-bin

stages:
    - prepare
    - build
    - verify
    - upload

.enable_sudo_nobody: &enable_sudo_nobody
        echo "nobody ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers                  # Enable sudo to work without prompting a password

.install_gitchangelog: &install_gitchangelog
        sudo pacman -Sy --noconfirm --needed python curl && sudo sh -c 'curl -sSL https://raw.githubusercontent.com/vaab/gitchangelog/master/src/gitchangelog/gitchangelog.py > /usr/local/bin/gitchangelog' && sudo chmod +x /usr/local/bin/gitchangelog

## This activates the use of the configured private keys in a build pipeline.
.enable_private_keys: &enable_private_keys
    ## Install ssh-agent if not already installed
    - 'which ssh-agent || sudo pacman -Sy --noconfirm --needed openssh'
  
    ## Run ssh-agent
    - eval $(ssh-agent -s)
  
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work without extra base64 encoding. (https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556)
    ##
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  
    ## Create the SSH directory and give it the right permissions
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  
    ## Set the user name and and email for git commands
    - git config --global user.email "unknown@unknown.com"
    - git config --global user.name "Gitlab CI Runner"
  
    ## Set known hosts using the configurable SSH_KNOWN_HOSTS variable
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

.pkgbuild:prepare: &pkgbuild_prepare
    stage: prepare
    variables:
        TARGETS: prepare install
        PREFIX: package-src
    script:
        - sudo pacman -Sy --noconfirm --needed make sed sudo git base-devel lsb-release
        - *install_gitchangelog
        - exec-helper build --target ${TARGETS} --prefix ${PWD}/${PREFIX}
    artifacts:
        expire_in: 1 day
        paths:
            - $PREFIX/*

.pkgbuild:build: &pkgbuild_build
    stage: build
    script: 
        - sudo pacman -Sy --noconfirm --needed base-devel sudo lsb-release make cmake
        - pushd ${PREFIX}
        - makepkg --noconfirm --check --needed --syncdeps --force
        - popd
        - mkdir -p ${BIN_PREFIX}
        - mv ${PREFIX}/*.tar.xz ${BIN_PREFIX}/
    artifacts:
        expire_in: 1 day
        paths:
            - ${BIN_PREFIX}/*

.pkgbuild:analyze: &pkgbuild_analyze
    stage: verify
    script:
        - sudo pacman -Sy --noconfirm --needed namcap
        - namcap ${PREFIX}/PKGBUILD
        - namcap ${PREFIX}/.SRCINFO
        - namcap ${BIN_PREFIX}/*.tar.xz

.pkgbuild:verify: &pkgbuild_verify
    stage: verify
    script:
        - sudo pacman -Sy
        - sudo pacman --needed --noconfirm -U ${BIN_PREFIX}/*.tar.xz

.pkgbuild:upload: &pkgbuild_upload
    stage: upload
    variables:
        URL: INVALID_URL.git
        PREFIX: package-src
        GIT_SUBMODULE_STRATEGY: none
    before_script:
        *enable_private_keys
    script:
        - sudo pacman -Sy --noconfirm --needed git
        - export SOURCE_HASH=$(git log -C rapidcheck -n 1 --pretty=format:"%H")
        - echo "Cloning ${URL}..."
        - git clone ${URL} repo
        - rm -rf repo/*
        - mv ${PREFIX}/* repo/
        - git -C repo add .
        - git -C repo diff-index --quiet HEAD -- && echo 'No changes -- skipping commit' || git -C repo commit -m "Updated package to commit ${SOURCE_HASH}"
        - git -C repo push

pkgbuild:prepare:
    <<: *pkgbuild_prepare
    image: bverhagen/exec-helper-package:arch-linux

pkgbuild:build:
    <<: *pkgbuild_build
    image: bverhagen/pacman-aur-wrapper
    dependencies:
        - pkgbuild:prepare

pkgbuild:analyze:
    <<: *pkgbuild_analyze
    image: bverhagen/pacman-aur-wrapper
    dependencies:
        - pkgbuild:prepare
        - pkgbuild:build

pkgbuild:verify:
    <<: *pkgbuild_verify
    image: bverhagen/pacman-aur-wrapper
    dependencies:
        - pkgbuild:build

upload:
    <<: *pkgbuild_upload
    image: bverhagen/pacman-aur-wrapper
    dependencies:
        - pkgbuild:prepare
    variables:
        URL: ssh://aur@aur.archlinux.org/rapidcheck.git
    only:
        - master
